### ISSUE TITLE
Waku-Rln-Relay Onchain Setup

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#1015]
This issue is part of https://github.com/status-im/nwaku/issues/827
Waku-rln-relay relies on a membership contract that should be deployed on the Ethereum blockchain as the group management layer. The membership contract acts as a registry and keeps track of the current members of the rln group. Waku nodes that are running waku-relay-protocol will obtain membership updates by listening to the contract's emitted events. The necessary logic related to event listening is already implemented in the nim-waku code. However, the contract deployment and a few other things are going to be covered in this issue.

 Below is the list of tasks to  be performed as part of this issue
- [x] The contract should be deployed to one of the Ethereum testnet e.g., Ropsten. Links to the contract is provided in the _resources_ section below.
- [x]  Preparing a tutorial on how to set up an account on the testnet  e.g., obtain ethers
- [x] Preparing instructions on how to use the testnet ethereum accounts to run waku nodes (the ethereum accounts will be used to send registration transactions to the contract). This part should be tested against a waku node. 

 A few other points to be investigated as part of this issue:
- Would it be possible to transact with the contract with no Ether (or is there any testnet that can allow such or with lower Ether cost?)
- What are the security considerations for the private key of Ethereum testnet accounts. In the current implementation, waku nodes need to pass the private key of the Ethereum testnet account  as a command-line option to the program, we need to make sure that does not pose users with some serious security/privacy issues, although the funds are not real.
 

**Some relevant resources**
- Waku-rln-relay paper https://github.com/vacp2p/research/blob/master/rln-research/Waku_RLN_Relay.pdf
- Waku-rln-relay specifications https://rfc.vac.dev/spec/17/
- The contract code https://github.com/status-im/nwaku/blob/master/waku/v2/protocol/waku_rln_relay/rln_relay_contract.nim (the bytecodes are already available in the supplied link)
- The source code of the membership contract that lives in another repo https://github.com/kilic/rlnapp/blob/master/packages/contracts/contracts/RLN.sol. Our version of the contract differs from this one where the parameters of the events are not `Indexed`, please see https://github.com/status-im/nwaku/blob/6c8ab0ab0f76fe765d95ef2f7bfb88d691a18bf7/waku/v2/protocol/waku_rln_relay/rln_relay_contract.nim#L16

**Comment by staheri14** [comment]
cc: @oskarth

**Comment by oskarth** [comment]
Probably makes sense to deploy to Goerli instead of Ropsten, since Ropsten is deprecated https://ethereum.org/en/developers/docs/networks/#goerli

**Comment by kgrgpg** [comment]
@oskarth Yes the contracts have now been deployed to Goerli testnet. The progress of this in detail can be tracked at 
https://hackmd.io/xj84_7hwRDKniQFXGOyGEQ?both

**Comment by staheri14** [comment]
@kgrgpg I see all the tasks for this issue are done, then the issue can be closed?

**Comment by kgrgpg** [comment]
Yes, that is correct. This issue can be closed. In general, who is responsible to close any issue? @staheri14

**Comment by staheri14** [comment]
Whoever addresses the issue can also close the issue. So in this case, since you have taken care of the issue, feel free to close it.  @kgrgpg
