### ISSUE TITLE
Upgrade nwaku to Nim `v1.6.6`

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#1033]
This issue may be more of an investigation than a singular task.

Quick exploration by @LNSD shows that compilation fails if setting the nimbus-build-system to Nim 1.6.6. This issue tracks effort to make this work and upgrade to Nim 1.6.6.

**Comment by LNSD** [comment]
@Menduist I remember from one of our offsite conversations that there's some limitation right now that prevents us from moving to Nim `v1.6.6`. Is libp2p supporting `v1.6.6` yet?

**Comment by Menduist** [comment]
libp2p supports 1.6.6
Nimbus briefly switched to 1.6.6, but it got rolled back because of a showstopper https://github.com/nim-lang/Nim/issues/20107 that has since been fixed, but not yet backported

**Comment by narimiran** [comment]
> fixed, but not yet backported

It is backported now.

**Comment by LNSD** [comment]
As per the discussion with @jm-clius yesterday, we are postponing the Nim upgrade for one of the subsequent releases. Removing it from the release/milestone v0.12.

**Comment by jm-clius** [comment]
Nim version bumped in submodule update: https://github.com/status-im/nwaku/pull/1307

Outstanding tasks for 1.6.6:
- [ ] top level {.push raises: [].}
- [ ] work through most important deprecated methods and other compiler warnings

**Comment by alrevuelta** [comment]
Closed in https://github.com/status-im/nwaku/pull/1307?

**Comment by jm-clius** [comment]
@LNSD I think we can consider this done (thanks to the extra tasks you did to improve compiler messages, correct raises requirements, etc.)? May still be minor tasks that come up, but we can deal with them as they arise. Feel free to reopen if disagree.
