### ISSUE TITLE
Abstraction of writing persistent RLN credentials to a modular proc

### ISSUE THREAD

**Issue by kgrgpg** [status-im/nwaku#1053]
There has been an issue with exception raised because of this proc in the RLN relay test while reading the persistent RLN credentials. This is as explained in https://github.com/status-im/nwaku/pull/1037/#issuecomment-1200552233

**Comment by staheri14** [comment]
More context is available in https://github.com/status-im/nwaku/pull/1037#discussion_r926609731

**Comment by rymnc** [comment]
Addressed in #1285
