### ISSUE TITLE
master build occur error

### ISSUE THREAD

**Issue by younk-zhao** [status-im/nwaku#1074]
when execute command:  make -j2 wakunode2, it show such error

/root/nwaku/waku/v2/node/dnsdisc/waku_dnsdisc.nim(20, 20) Error: cannot open file: discovery/dnsdisc/client
stack trace: (most recent call last)
/root/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(416, 18)
/root/nwaku/waku.nimble(67, 15) wakunode2Task
/root/nwaku/waku.nimble(34, 8) buildBinary
/root/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) exec
/root/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(260, 7) Error: unhandled exception: FAILED: nim c --out:build/wakunode2 -d:chronicles_log_level=DEBUG --verbosity:0 --hints:off -d:release -d:discv5_protocol_id:d5waku -d:git_version:"v0.10-43-g4f9351" waku/v2/node/wakun

**Comment by jm-clius** [comment]
Hi @younk-zhao, thanks for reporting.
I can confirm that on a clean checkout of the `master` branch compilation is successful (at least on Debian/Linux), so it may be a local issue on your side.

A couple of things you can try:
1. Try running `make clean` and `make update` from your source folder and then execute the `make` command again.
2. `rm -rf` the `/nwaku/vendor/` subdirectory and run `make update`.
3. Do a clean clone of the `nwaku` repository (hopefully it doesn't come to this! :) )

LMK how it goes. 🙃

**Comment by jm-clius** [comment]
Closing this issue. Feel free to LMK if you still encounter issues and reopen if necessary.
