### ISSUE TITLE
The development roadmap of Waku store protocol incentivization using service credentials

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#1099]
This meta issue embodies the development roadmap of achieving https://github.com/vacp2p/research/issues/99
At a high level, we need to take care of the following main components:
- Game theoretical analysis of the payment flow to make sure that both parties rationally would follow protocol specifications (act honestly) to profit from their interaction
- Core anonymous payment implementation: Proper circuit with the associated zkSNARKs proof generation and verification should be developed and integrated into nwaku so that the payment proof can be generated and consumed. 
- Payment contract and on-chain interactions: The other part is to deploy a smart contract and allow querying node to obtain credentials by interacting with the contract. The service provider would be also able to withdraw the fund associated with its service by handing in the obtained credentials.  

## Milestones 
In terms of user stories and milestones, we can proceed as follows. Note that phase1 and 2 can be pursued in parallel.
- **Phase1, Core implementation with mocked on-chain interaction**:  This phase focuses on the circuit part of the payment. No contract deployment is needed, instead, a list of service credentials is hardcoded with known `k` and `r` values (the secrets for credential transfer).  A Merkle tree is constructed based on the hardcoded list. The querying peer selects a credential from the hard-coded list  and constructs a valid transfer proof and sends it alongside its HistoryQuery.  The querier sends one credential per request regardless of the amount of queried data. The payment is done upfront by the querier. The receiver should verify the credential transfer and update the tree (the querying node should also update its tree). 
  - Raw RFC
  - zero-kit implementation of the circuits
  - Integration of the corresponding zkSNARKs proof into nim implementation 
  - Updating the store protocol to handle the minimal payment model as set out for the phase1
  - Dogfooding
 - **Phase2, game-theoretic solid payment flow:** This milestone is to study the game theory behind the flow of payment to make sure the two parties have enough at stake / or are incentivized enough to follow the protocol specifications.
   - A game theoretic analysis of the payment protocol, potentially publishing the result as a forum/research post
   - Updating the RFC if needed
   - Updating the implementation in nwaku if needed
- **Phase3, On-chain payment**: Developing the smart contract, having it deployed on a testnet, and replacing the hardcoded list of credentials and Merkle tree with proper calls to the smart contract.
  - Updating the RFC
  - Developing the smart contract
  - Developing necessary code to consume the contract from the nim side
  - Functional test and dogfooding

In terms of task distribution, phase1 would be mainly run by @s1fr0, phase2 by @staheri14, and phase3 by both @staheri14 and @s1fr0.

**Comment by staheri14** [comment]
Once we agree on the general roadmap, we can follow up with individual milestone issues.

**Comment by fryorcraken** [comment]
@staheri14 does this really belong in the nwaku repo? looking at phase 1 for example:

- raw rfc (rfc repo)
- zerokit implementation (zerokit repo)
- Integration of the corresponding zkSNARKs proof into nim implementation (nwaku)
etc

Wouldn't it make more sense to keep this in the vacp2p/research repo and only open nwaku implementation specific steps in the nwaku repo?

**Comment by jm-clius** [comment]
I agree with @fryorcraken that this is probably a research issue (that will likely spinoff many nwaku issues). :) Should be possible to move quite easily if you agree, @staheri14?

**Comment by staheri14** [comment]
@jm-clius @fryorcraken sure, moving the issue to the vacp2p/research repo https://github.com/vacp2p/research/issues/135
