### ISSUE TITLE
Chore: Update submodules

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#1102]
## Problem

It's been a while since we last updated submodules. An [ongoing effort](https://github.com/status-im/nwaku/pull/1038) revealed that some breaking changes in submodules, notable `libp2p` requires fairly invasive changes in `nwaku`. A list of necessary changes can be found there.

## Acceptance criteria

- [ ] all submodules updated
- [ ] breaking changes address in `nwaku` code

**Comment by jm-clius** [comment]
Quick check shows that this issue is blocked until:
1. https://github.com/status-im/nim-libp2p/pull/754 is merged (reason: our current workaround is to mount, but not start, `relay` on all nodes, but this does not work anymore as all mounted protocols should be started since https://github.com/status-im/nim-libp2p/commit/0ece5eaf121bd58b790252f820c1829ac224f5f3)
2. the submodule for nim-eth points to [master again](https://github.com/status-im/nwaku/blob/3f7aa8c6e4a718f1ce5a5b9d98f0817e067850d9/.gitmodules#L5)

**Comment by Menduist** [comment]
754 is now merged
