### ISSUE TITLE
store: simplify configuration options

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#1103]
## Background

Currently `store` configuration is quite confusing:
`--store` needs to be enabled, even if a node is only a store client
`--persist-messages` needs to be enabled to store historical messages as a store service node, even if messages are not persisted in DB
`--db-path` is required to actually persist messages on disk

See [this guide](https://github.com/status-im/nwaku/blob/ad7f9ed5bfe5c47cd581149a20def03d019b82a6/docs/operators/how-to/configure-store.md#configuring-a-store-client) for more.

## Suggested solution

It makes much more sense to me this way: `store` should in fact only be mounted if you are storing messages yourself and this implies:
- only the `--store` config option is necessary (the confusing `--persist-messages` can be removed <-- this can probably be done in any case)
- store query API methods should always be available, as it's unrelated to whether `store` is mounted or not.

This has been discussed before in the context of [advertising store protocol](https://github.com/status-im/go-waku/issues/292#issuecomment-1227474687) and [handling asymmetrical protocols in libp2p](https://github.com/status-im/nim-libp2p/issues/568)

**Comment by LNSD** [comment]
Currently, we have several configuration options that have an indirect/direct effect on the waku store protocol. For `wakunode2` (eventually `nwaku` binary), we should aim to simplify the configuration with sensible but opinionated defaults.

Current node configuration options include:

> ### Persistence config
> 
> - _**dbPath**_ - Database file path
> - _**dbVacuum**_ - Enable/disable database vacuuming at node startup
> - _**persistPeers**_ - Enable/disable peer persistence
> - _**persistMessages**_ - Enable/disable message persistence
> 
> ### Waku store config
> 
> - _**store**_ - Enable/disable store protocol server
> - _**storenode**_ - Multiaddr of the node to query from
> - _**storeCapacity**_ - Max number of messages to keep in store
> - _**sqliteStore**_ - Enable SQLite-only store
> - _**sqliteRetentionTime**_ - SQLite only store message retention time

**Comment by LNSD** [comment]
My initial proposal:

> **Database configuration:**
> 
> - _**dbUrl**_ - database URL to specify the engine and the configuration (SQLAlchemy-like). It should default to `sqlite://store.sqlite3`.* If an invalid value is provided, the app should error out and exit.
> - ***dbVaccum*** - Enable/disable SQLite database vacuuming at node startup. Only if using SQLite database engine; otherwise, ignore.
> - ***dbMigration*** - Enable/disable database migrations at node startup.
> 
> **Node/Network configuration:**
> 
> - _**persistPeers**_ - Enable/disable peer nodes persistence.
> 
> **Message store configuration:**
> 
> - ***messageStore*** - Multi-option configuration selector: `none|sqlite|memory|dual`. `none` option should disable message storage.
> - ***messageRetentionPolicy*** - Multi-option configuration selector:
>     - Time retention policy: `time:30days`
>     - Capacity retention policy: `capacity:25000`
> 
> **Resume-at-boot configuration (alpha):**
> 
> - ***messageStoreResumePeer*** - Peer *multiaddress* to resume the message store at boot. If not set, the *resume-at-boot* functionality should be disabled.
> 
> **Waku store protocol:**
> 
> - ***store*** - Enable/disable the waku store protocol server. If the store protocol is enabled, but the message store is disabled (set to `none`), do not start the store protocol.
>

**Comment by LNSD** [comment]
There are several constraints that make the configuration complex (in both cases):

- The `persistPeers` configuration depends on the _database configuration_ since the peers are persisted in the SQLite store.
- The `messageStore` can depend (or not) on the _database configuration_, depending on the desired message store implementation.
- The `messageRetentionPolicy` requires a specific message store implementation to be present. Same as the original `storeCapacity` or `sqliteRetentionTime` config options.

**Comment by LNSD** [comment]
A more straightforward and opinionated configuration:

> ### Database configuration:
> 
> - ***dbUrl*** - database URL to specify the engine and the configuration (SQLAlchemy-like). It should default to `sqlite://store.sqlite3`.* If an invalid value is provided, the app should error out and exit. If explicitly set to `“”`, do not provide any database connection.
> - ***dbVaccum*** - Enable/disable SQLite database vacuuming at node startup. Only if using SQLite database engine; otherwise, ignore.
> - ***dbMigration*** - Enable/disable database migrations at node startup. Only if any database engine is configured.
> 
> ### Node/Network configuration:
> 
> - ************************************persistPeers************************************ - Enable/disable peer nodes persistence.  If **DB** is disabled (the ***dbUrl*** config is ******set to `""`), then this configuration option should be ignored.
> 
> ### Waku store protocol:
> 
> - ***store*** - Enable/disable the waku store protocol server. If the store protocol is enabled, the message store should use the SQLite implementation by default. If the database is disabled (the ***dbUrl*** config is set to `""`), then fallback to the in-memory store implementation. Dual store implementation does not fit any case.
> - ***storeConcurrentQueriesLimit*** - Max concurrent queries limit. Not implemented yet.
> - ***storeMessageRetentionPolicy*** - Message retention policy. Multi-option configuration selector:
>     - Time retention policy: `time:<duration>` (e.g., `--store-message-retention-policy=time:2days`)
>     - Capacity retention policy: `capacity:<count>` (e.g., `--store-message-retention-policy=capacity:15000`)
> - ***storeResumePeer*** - Peer *multiaddress* to resume the message store at boot. If not set, the *resume-at-boot* functionality should be disabled.

**Comment by jakubgs** [comment]
I like the grouping of DB, peer, and store options under their own namespaces. Though we probably would want `persistPeers` to be `peersPersistence`/`--peer-persistence` since there are other flags that also should be under that namespace, like `--peer-exchange` or something like `--peer-max`(which I believe doesn't exist yet).

**Comment by LNSD** [comment]
For now, we are keeping the database migrations as part of the node start process. This is very likely to change in the near future. But with the option of skipping the migrations if necessary.

We are evaluating moving the database migrations to a separate step before upgrading the nwaku node version.

**Comment by jm-clius** [comment]
Thanks for tackling this! It's high time that `--store` should only be configured on store servers. I especially like the single `--storeMessageRetentionPolicy` config item in your suggestion.

A couple of comments:
- "Dual store implementation does not fit any case" - are you suggesting that we should never configure a dual store? I.e. only configure either SQLite store for persistence or an in-memory store?
- `storeResumePeer` <-- I'm assuming this becomes a separate configuration from `storenode` to address the different use cases? I'm not convinced that this is necessary - for one, we want to eventually be able to use any store service node in the peer store to resume from (possibly in conjunction with some capability discovery mechanism). The peer store would then expose a `selectPeer(protocol, capabilities[])` method which returns the "best" service node that supports the selected protocol and capabilities. Perhaps then only a `--storeResume` boolean to enable/disable resuming on store init?
- I agree with Jakub's suggestion re `--peer-persistence`

**Comment by jm-clius** [comment]
Sounds reasonable to me. Afaik existing store nodes (even from operators) are all now using the sqlite-only option. I can see the in-memory option being useful for short-term caching across the network, but no immediate need for persistence.

**Comment by jm-clius** [comment]
Thanks! I'll work on synthesising this with some of the requirements that we're busy compiling for peer management, partially being documented in https://github.com/status-im/nwaku/issues/622

> I am working towards support specifying the node to query from as part of the API call

I like this, as it carries the implication that these peers should be managed by the application.

**Comment by fryorcraken** [comment]
> persistPeers - Enable/disable peer nodes persistence. If the database is disabled, this configuration option should be ignored.

I would suggest to fail and not ignore so that a user does not expect to have peers persisting when db is not enabled.

**Comment by LNSD** [comment]
I am going to decouple peer persistence from the message store database connection. We might want to support, in the near future, local peer persistence but maybe share the message store DB.

Given that we have not merged #1293 yet. This is the new configuration I propose:

> ### Node/Network configuration:
> 
> - ***peerPersistence*** - Enable/disable peer nodes persistence. Peer persistence will have a dedicated SQLite file: `sqlite://peers.db`.
> 
> ### Waku store protocol and message store:
> 
> - ***store*** - Enable/disable the waku store protocol server. If the store protocol is enabled, the message store should use the SQLite implementation by default. If the database is disabled, then fallback to the in-memory store implementation. Dual store implementation does not fit any case.
> - ***storeConcurrentQueriesLimit*** - Max concurrent queries limit. Not implemented yet.
> - ***storeMessageRetentionPolicy*** - Message retention policy. Multi-option configuration selector:
>     - Time retention policy: `time:<duration>` (e.g., `--store-message-retention-policy=time:2days`)
>     - Capacity retention policy: `capacity:<count>` (e.g., `--store-message-retention-policy=capacity:15000`)
> - ***storeMessageDbUrl*** - Message store database URL to specify the engine and the configuration (SQLAlchemy-like). It should default to `sqlite://store.sqlite3`. If an invalid value is provided, the app should error out and exit. If explicitly set to `""`, do not provide any database connection.
> - ***storeMessageDbVacuum*** - Enable/disable message store SQLite database vacuuming at node startup. Only if using SQLite database engine; otherwise, ignore.
> - ***storeMessageDbMigration*** - Enable/disable message store database migrations at node startup. Only if any database engine is configured.
> - ***storeResumePeer*** - Peer *multiaddress* to resume the message store at boot. If not set, the *resume-at-boot* functionality should be disabled.

**Comment by jm-clius** [comment]
I agree with this direction. `peerPersistence` should be decoupled in configuration.
