### ISSUE TITLE
chore: add `version` gauge to metrics

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#1125]
### Background

To increase the visibility of the nwaku `version` from a monitoring perspective, we need to add this as a metric label somewhere. We could follow the same route as nimbus and simply [declare a gauge specifically for this purpose](https://github.com/status-im/nimbus-eth2/blob/3a8abd60108ff94b340620e2b12fd2cb7229ffbe/beacon_chain/nimbus_beacon_node.nim)

### Acceptance criteria
- [ ] nwaku version and/or commit hash logged as label in metric
- [ ] Grafana dashboard updated to make this visible

**Comment by jakubgs** [comment]
Still waiting...
