### ISSUE TITLE
bug: CPU spikes/stalls in some deployed `nwaku` instances

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#1127]
### Problem

One some deployed fleets, notably `status.test` CPU spikes are visible and nodes become unresponsive from time to time.

### Impact

Significant. Impact includes:
- failure to process, relay and store messages during periods of unresponsiveness
- failure to accept incoming connections

### To reproduce

Not yet reproduced locally. Visible on higher traffic fleets, such as status.test

### Screenshots/logs

Shows 90 day period, where increase in CPU usage since ~23 Aug becomes clear:

![image](https://user-images.githubusercontent.com/68783915/188914188-3ec48355-2287-4fca-b15a-0eef18f9d1e4.png)

although message rates have not changed too much:

![image](https://user-images.githubusercontent.com/68783915/188914433-1e50b567-bdf2-4a7b-87c2-16769f1aad76.png)

### nwaku version/commit hash

Reported since `v0.11`.

### Additional context

Relates to https://github.com/status-im/status-web/issues/305

**Comment by fryorcraken** [comment]
proposed work around: use `status.prod` fleet.

**Comment by LNSD** [comment]
@jm-clius identified yesterday that the issue is very likely to be caused by a regression introduced in #1120. The `i_rt` index was dropped. PR #1136 restores the `i_rt` index, so we expect insertion time and CPU usage to return to normal values.

**Comment by LNSD** [comment]
We can conclude that the changes done in #1136 have solved the CPU spikes and have solved the regression. I proceed to resolve this issue.
