### ISSUE TITLE
chore: Github CI failures

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#1131]
### Background

Github CI test workflows for nwaku have been failing since a [recent submodule update](https://github.com/status-im/nwaku/actions/runs/3008298998). This is because the tests are now so slow that they time out after 1 hour on the `macos-latest` platform and get cancelled.

### Details

There are several avenues to explore here:
- considering moving exclusively to a more configurable Jenkins CI environment (we already have the tests set up here: https://ci.status.im/job/nim-waku/job/prs/)
- improve individual test run times, remove unnecessary `sleep`s etc.
- parallelize tests (or schedule tests better)

### Acceptance criteria

- [ ] Regular CI passes for each PR

**Comment by LNSD** [comment]
Reducing the "async sleep" time is a low-hanging fruit. I am reducing to 500ms the 2000ms static sleeps as I progress with my refactorings. For example, in a test suite, I counted 2 mins in total just waiting for something to happen in the test case. 

As a side note: In testing, it is usually discouraged to do a static sleep unless it is the only way of testing something (e.g., the static awaits can mask some race conditions). A good practice is to use dynamic awaits (e.g., poll periodically for certain events to happen with a timeout). And if the language supports the async/await style, much better 😁

**Comment by rymnc** [comment]
Update:

Able to reproduce on a machine with the following spec -
```
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83
```

Commands to reproduce -
```bash
make wakunode2
./build/wakunode2
```

OR

```bash
make chat2
./build/chat2
```

Investigations:

1. The OS version did not change between the last successful run and the latest run - hence it is not an OS *version* related issue (or that we use `latest` version in the build strategy)
2. Interesting that after running

    `make test2 RLN=true` works, every subsequent `make test2` works
    
3. chat2 is able to compile on two machines (having the same spec), however, doesn't run on one, and runs on the other. I imagine this is a good starting point to figure out what's going on here
