### ISSUE TITLE
bug: missing messages in Waku v2 store nodes

### ISSUE THREAD

**Issue by felicio** [status-im/nwaku#1146]
### Problem
Missing messages in Waku v2 store nodes, `status.test` fleet.

### Impact
- `critical`

### To reproduce
1. Query respective nodes (see "Screenshots/logs" section)
2. Compare responses/messages (e.g. without decoding and decrypting – payload bytes, timestamp, or signature)

### Expected behavior
To receive same messages from all of the store nodes.

### Screenshots/logs
Following returns `0` message(s):
https://kibana.infra.status.im/goto/374f5430-3341-11ed-b14f-29f692784ff2

Following returns `1` message(s):
https://kibana.infra.status.im/goto/93627ef0-3341-11ed-b14f-29f692784ff2

<details>
  <summary>Show message(s)</summary>
  <pre>
		<code>
{
  proto: {
    payload: new Uint8Array([10, 65, 168, 10, 149, 83, 81, 79, 234, 192, 229, 103, 83, 37, 163, 205, 199, 90, 104, 31, 128, 255, 212, 188, 225, 88, 89, 78, 66, 236, 136, 239, 141, 59, 82, 68, 88, 215, 99, 13, 244, 64, 155, 145, 71, 153, 107, 196, 201, 183, 85, 34, 13, 160, 89, 69, 189, 128, 188, 111, 127, 134, 143, 192, 228, 109, 0, 18, 165, 1, 8, 207, 240, 147, 137, 179, 48, 16, 208, 240, 147, 137, 179, 48, 26, 9, 102, 114, 111, 109, 58, 32, 119, 101, 98, 34, 0, 42, 0, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1, 74, 4, 10, 0, 16, 0, 82, 4, 10, 0, 16, 2, 90, 6, 10, 0, 16, 1, 24, 0, 98, 0, 106, 0, 114, 0, 24, 1]),
    contentTopic: "/waku/1/0x0fd9cba5/rfc26",
    version: 1,
    timestamp: 1662976850017999872n,
  },
  _signaturePublicKey: new Uint8Array([4, 94, 214, 244, 124, 13, 194, 106, 19, 158, 97, 200, 246, 144, 243, 115, 58, 191, 10, 159, 121, 137, 233, 55, 86, 75, 45, 204, 3, 208, 168, 169, 108, 146, 0, 31, 119, 113, 134, 233, 186, 2, 185, 242, 40, 172, 213, 185, 51, 158, 232, 101, 116, 245, 136, 211, 131, 76, 21, 196, 90, 34, 213, 85, 231]),
  _signature: new Uint8Array([238, 126, 121, 92, 214, 152, 223, 75, 143, 47, 206, 33, 83, 250, 146, 146, 185, 55, 106, 73, 134, 123, 44, 247, 23, 100, 110, 30, 101, 28, 243, 95, 92, 74, 67, 73, 0, 81, 26, 68, 202, 214, 228, 241, 89, 152, 51, 171, 226, 6, 152, 85, 215, 234, 46, 41, 1, 29, 224, 114, 173, 180, 77, 125, 1]),
}
{
  signature: new Uint8Array([168, 10, 149, 83, 81, 79, 234, 192, 229, 103, 83, 37, 163, 205, 199, 90, 104, 31, 128, 255, 212, 188, 225, 88, 89, 78, 66, 236, 136, 239, 141, 59, 82, 68, 88, 215, 99, 13, 244, 64, 155, 145, 71, 153, 107, 196, 201, 183, 85, 34, 13, 160, 89, 69, 189, 128, 188, 111, 127, 134, 143, 192, 228, 109, 0]),
  payload: new Uint8Array([8, 207, 240, 147, 137, 179, 48, 16, 208, 240, 147, 137, 179, 48, 26, 9, 102, 114, 111, 109, 58, 32, 119, 101, 98, 34, 0, 42, 0, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1, 74, 4, 10, 0, 16, 0, 82, 4, 10, 0, 16, 2, 90, 6, 10, 0, 16, 1, 24, 0, 98, 0, 106, 0, 114, 0]),
  type: "TYPE_CHAT_MESSAGE",
}
{
  clock: 1662976849999n,
  timestamp: 1662976850000n,
  text: "from: web",
  responseTo: "",
  ensName: "",
  chatId: "0x029f196bbfef4fa6a5eb81dd802133a63498325445ca1af1d154b1bb454295513330804ea7-bd66-4d5d-91eb-b2dcfe2515b3",
  messageType: "COMMUNITY_CHAT",
  contentType: "TEXT_PLAIN",
  sticker: {
    hash: "",
    pack: 0,
  },
  image: {
    payload: new Uint8Array([]),
    type: "JPEG",
  },
  audio: {
    payload: new Uint8Array([]),
    type: "AAC",
    durationMs: 0n,
  },
  community: new Uint8Array([]),
  grant: new Uint8Array([]),
  displayName: "",
}			
		</code>
	</pre>
</details>

Following returns `3` message(s):
https://kibana.infra.status.im/goto/9315a200-3342-11ed-b14f-29f692784ff2

<details>
  <summary>Show message(s)</summary>
  <pre>
		<code>
{
  proto: {
    payload: new Uint8Array([10, 65, 168, 10, 149, 83, 81, 79, 234, 192, 229, 103, 83, 37, 163, 205, 199, 90, 104, 31, 128, 255, 212, 188, 225, 88, 89, 78, 66, 236, 136, 239, 141, 59, 82, 68, 88, 215, 99, 13, 244, 64, 155, 145, 71, 153, 107, 196, 201, 183, 85, 34, 13, 160, 89, 69, 189, 128, 188, 111, 127, 134, 143, 192, 228, 109, 0, 18, 165, 1, 8, 207, 240, 147, 137, 179, 48, 16, 208, 240, 147, 137, 179, 48, 26, 9, 102, 114, 111, 109, 58, 32, 119, 101, 98, 34, 0, 42, 0, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1, 74, 4, 10, 0, 16, 0, 82, 4, 10, 0, 16, 2, 90, 6, 10, 0, 16, 1, 24, 0, 98, 0, 106, 0, 114, 0, 24, 1]),
    contentTopic: "/waku/1/0x0fd9cba5/rfc26",
    version: 1,
    timestamp: 1662976850017999872n,
  },
  _signaturePublicKey: new Uint8Array([4, 94, 214, 244, 124, 13, 194, 106, 19, 158, 97, 200, 246, 144, 243, 115, 58, 191, 10, 159, 121, 137, 233, 55, 86, 75, 45, 204, 3, 208, 168, 169, 108, 146, 0, 31, 119, 113, 134, 233, 186, 2, 185, 242, 40, 172, 213, 185, 51, 158, 232, 101, 116, 245, 136, 211, 131, 76, 21, 196, 90, 34, 213, 85, 231]),
  _signature: new Uint8Array([238, 126, 121, 92, 214, 152, 223, 75, 143, 47, 206, 33, 83, 250, 146, 146, 185, 55, 106, 73, 134, 123, 44, 247, 23, 100, 110, 30, 101, 28, 243, 95, 92, 74, 67, 73, 0, 81, 26, 68, 202, 214, 228, 241, 89, 152, 51, 171, 226, 6, 152, 85, 215, 234, 46, 41, 1, 29, 224, 114, 173, 180, 77, 125, 1]),
}
{
  signature: new Uint8Array([168, 10, 149, 83, 81, 79, 234, 192, 229, 103, 83, 37, 163, 205, 199, 90, 104, 31, 128, 255, 212, 188, 225, 88, 89, 78, 66, 236, 136, 239, 141, 59, 82, 68, 88, 215, 99, 13, 244, 64, 155, 145, 71, 153, 107, 196, 201, 183, 85, 34, 13, 160, 89, 69, 189, 128, 188, 111, 127, 134, 143, 192, 228, 109, 0]),
  payload: new Uint8Array([8, 207, 240, 147, 137, 179, 48, 16, 208, 240, 147, 137, 179, 48, 26, 9, 102, 114, 111, 109, 58, 32, 119, 101, 98, 34, 0, 42, 0, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1, 74, 4, 10, 0, 16, 0, 82, 4, 10, 0, 16, 2, 90, 6, 10, 0, 16, 1, 24, 0, 98, 0, 106, 0, 114, 0]),
  type: "TYPE_CHAT_MESSAGE",
}
{
  clock: 1662976849999n,
  timestamp: 1662976850000n,
  text: "from: web",
  responseTo: "",
  ensName: "",
  chatId: "0x029f196bbfef4fa6a5eb81dd802133a63498325445ca1af1d154b1bb454295513330804ea7-bd66-4d5d-91eb-b2dcfe2515b3",
  messageType: "COMMUNITY_CHAT",
  contentType: "TEXT_PLAIN",
  sticker: {
    hash: "",
    pack: 0,
  },
  image: {
    payload: new Uint8Array([]),
    type: "JPEG",
  },
  audio: {
    payload: new Uint8Array([]),
    type: "AAC",
    durationMs: 0n,
  },
  community: new Uint8Array([]),
  grant: new Uint8Array([]),
  displayName: "",
}
		</code>
  </pre>
  <pre>
    <code>
{
  proto: {
    payload: new Uint8Array([18, 36, 49, 49, 48, 54, 50, 101, 102, 50, 45, 48, 48, 55, 52, 45, 52, 98, 55, 102, 45, 57, 54, 57, 48, 45, 49, 56, 99, 57, 56, 55, 48, 101, 56, 101, 52, 53, 26, 193, 1, 10, 33, 3, 172, 65, 157, 172, 154, 139, 187, 88, 130, 90, 60, 222, 96, 238, 240, 238, 113, 184, 207, 108, 99, 223, 97, 30, 238, 252, 142, 122, 172, 124, 121, 181, 18, 79, 10, 36, 49, 49, 48, 54, 50, 101, 102, 50, 45, 48, 48, 55, 52, 45, 52, 98, 55, 102, 45, 57, 54, 57, 48, 45, 49, 56, 99, 57, 56, 55, 48, 101, 56, 101, 52, 53, 18, 39, 10, 33, 3, 180, 72, 154, 221, 227, 137, 48, 36, 55, 243, 235, 109, 226, 186, 144, 61, 25, 112, 78, 8, 164, 235, 223, 186, 254, 52, 171, 4, 172, 78, 46, 150, 16, 61, 24, 1, 34, 65, 215, 192, 26, 116, 190, 17, 164, 35, 154, 90, 104, 20, 97, 122, 11, 241, 111, 88, 189, 29, 51, 113, 170, 25, 114, 71, 152, 158, 130, 164, 95, 46, 59, 223, 193, 200, 34, 30, 190, 192, 214, 218, 103, 19, 109, 21, 113, 21, 147, 64, 189, 248, 191, 232, 54, 156, 17, 151, 195, 208, 250, 145, 32, 69, 0, 40, 176, 180, 145, 250, 214, 231, 145, 137, 23, 178, 6, 202, 1, 10, 65, 62, 183, 103, 40, 140, 191, 230, 223, 80, 44, 138, 194, 18, 74, 76, 125, 179, 91, 124, 11, 158, 194, 133, 172, 225, 175, 149, 9, 23, 93, 166, 168, 97, 43, 194, 177, 99, 69, 57, 145, 189, 166, 156, 242, 165, 120, 215, 249, 80, 163, 93, 139, 251, 224, 71, 50, 175, 38, 202, 231, 162, 52, 63, 63, 0, 18, 130, 1, 8, 163, 158, 160, 151, 177, 48, 16, 163, 158, 160, 151, 177, 48, 26, 4, 112, 114, 111, 100, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1, 24, 1]),
    contentTopic: "/waku/1/0x0fd9cba5/rfc26",
    version: 1,
    timestamp: 1662469541000000000n,
  },
  _signaturePublicKey: new Uint8Array([4, 172, 65, 157, 172, 154, 139, 187, 88, 130, 90, 60, 222, 96, 238, 240, 238, 113, 184, 207, 108, 99, 223, 97, 30, 238, 252, 142, 122, 172, 124, 121, 181, 89, 84, 182, 121, 210, 76, 245, 236, 130, 218, 126, 217, 33, 202, 242, 64, 98, 138, 155, 251, 52, 80, 197, 17, 26, 156, 255, 229, 78, 99, 24, 17]),
  _signature: new Uint8Array([207, 172, 12, 48, 106, 154, 1, 204, 226, 136, 145, 232, 164, 180, 94, 210, 148, 158, 169, 80, 124, 31, 12, 72, 228, 105, 21, 235, 143, 20, 113, 82, 102, 165, 159, 134, 62, 4, 138, 11, 82, 241, 115, 179, 25, 44, 207, 65, 144, 16, 219, 16, 188, 111, 32, 223, 229, 90, 107, 50, 192, 201, 158, 235, 1]),
}
{
  signature: new Uint8Array([62, 183, 103, 40, 140, 191, 230, 223, 80, 44, 138, 194, 18, 74, 76, 125, 179, 91, 124, 11, 158, 194, 133, 172, 225, 175, 149, 9, 23, 93, 166, 168, 97, 43, 194, 177, 99, 69, 57, 145, 189, 166, 156, 242, 165, 120, 215, 249, 80, 163, 93, 139, 251, 224, 71, 50, 175, 38, 202, 231, 162, 52, 63, 63, 0]),
  payload: new Uint8Array([8, 163, 158, 160, 151, 177, 48, 16, 163, 158, 160, 151, 177, 48, 26, 4, 112, 114, 111, 100, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1]),
  type: "TYPE_CHAT_MESSAGE",
}
{
  clock: 1662469541667n,
  timestamp: 1662469541667n,
  text: "prod",
  chatId: "0x029f196bbfef4fa6a5eb81dd802133a63498325445ca1af1d154b1bb454295513330804ea7-bd66-4d5d-91eb-b2dcfe2515b3",
  messageType: "COMMUNITY_CHAT",
  contentType: "TEXT_PLAIN",
}
    </code>
  </pre>
  <pre>
    <code>
{
  proto: {
    payload: new Uint8Array([18, 36, 97, 101, 50, 102, 53, 98, 55, 101, 45, 54, 100, 101, 51, 45, 53, 54, 97, 53, 45, 56, 49, 54, 101, 45, 52, 102, 97, 55, 101, 53, 52, 48, 100, 56, 102, 53, 26, 193, 1, 10, 33, 2, 148, 197, 104, 4, 137, 223, 84, 88, 195, 217, 246, 181, 76, 105, 34, 232, 250, 239, 169, 40, 83, 136, 170, 1, 124, 121, 55, 181, 150, 43, 112, 121, 18, 79, 10, 36, 97, 101, 50, 102, 53, 98, 55, 101, 45, 54, 100, 101, 51, 45, 53, 54, 97, 53, 45, 56, 49, 54, 101, 45, 52, 102, 97, 55, 101, 53, 52, 48, 100, 56, 102, 53, 18, 39, 10, 33, 2, 44, 51, 32, 252, 83, 251, 86, 193, 22, 140, 5, 131, 130, 152, 147, 8, 155, 49, 77, 59, 147, 65, 242, 251, 237, 250, 55, 58, 227, 71, 104, 135, 16, 38, 24, 1, 34, 65, 158, 59, 81, 81, 194, 215, 147, 122, 40, 8, 244, 123, 244, 182, 65, 76, 216, 11, 254, 86, 114, 79, 124, 12, 206, 192, 184, 231, 243, 5, 97, 38, 86, 254, 24, 235, 56, 219, 232, 175, 63, 7, 198, 97, 39, 208, 25, 79, 78, 249, 215, 227, 112, 192, 164, 201, 196, 180, 134, 104, 234, 156, 126, 154, 0, 40, 248, 201, 209, 221, 207, 229, 145, 137, 23, 178, 6, 202, 1, 10, 65, 83, 18, 121, 115, 84, 184, 90, 39, 165, 150, 174, 6, 111, 166, 75, 224, 150, 183, 51, 40, 153, 81, 177, 52, 188, 215, 126, 120, 220, 52, 51, 177, 10, 156, 199, 209, 155, 95, 117, 144, 167, 40, 114, 136, 93, 142, 198, 232, 244, 129, 216, 229, 199, 136, 126, 99, 9, 28, 41, 223, 7, 3, 196, 156, 0, 18, 130, 1, 8, 255, 245, 155, 151, 177, 48, 16, 255, 245, 155, 151, 177, 48, 26, 4, 84, 101, 115, 116, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1, 24, 1]),
    contentTopic: "/waku/1/0x0fd9cba5/rfc26",
    version: 1,
    timestamp: 1662469470000000000n,
  },
  _signaturePublicKey: new Uint8Array([4, 148, 197, 104, 4, 137, 223, 84, 88, 195, 217, 246, 181, 76, 105, 34, 232, 250, 239, 169, 40, 83, 136, 170, 1, 124, 121, 55, 181, 150, 43, 112, 121, 14, 142, 76, 23, 46, 185, 35, 102, 139, 19, 124, 48, 253, 113, 180, 105, 119, 48, 78, 217, 56, 167, 157, 171, 98, 14, 135, 250, 32, 189, 182, 110]),
  _signature: new Uint8Array([37, 26, 135, 19, 47, 210, 153, 216, 247, 227, 204, 231, 230, 140, 111, 226, 237, 240, 233, 78, 162, 169, 20, 56, 98, 56, 233, 136, 9, 11, 10, 117, 87, 202, 188, 97, 166, 228, 191, 250, 74, 11, 182, 165, 148, 39, 87, 171, 76, 87, 90, 0, 179, 196, 159, 147, 39, 201, 2, 50, 242, 57, 179, 43, 0]),
}
{
  signature: new Uint8Array([83, 18, 121, 115, 84, 184, 90, 39, 165, 150, 174, 6, 111, 166, 75, 224, 150, 183, 51, 40, 153, 81, 177, 52, 188, 215, 126, 120, 220, 52, 51, 177, 10, 156, 199, 209, 155, 95, 117, 144, 167, 40, 114, 136, 93, 142, 198, 232, 244, 129, 216, 229, 199, 136, 126, 99, 9, 28, 41, 223, 7, 3, 196, 156, 0]),
  payload: new Uint8Array([8, 255, 245, 155, 151, 177, 48, 16, 255, 245, 155, 151, 177, 48, 26, 4, 84, 101, 115, 116, 50, 104, 48, 120, 48, 50, 57, 102, 49, 57, 54, 98, 98, 102, 101, 102, 52, 102, 97, 54, 97, 53, 101, 98, 56, 49, 100, 100, 56, 48, 50, 49, 51, 51, 97, 54, 51, 52, 57, 56, 51, 50, 53, 52, 52, 53, 99, 97, 49, 97, 102, 49, 100, 49, 53, 52, 98, 49, 98, 98, 52, 53, 52, 50, 57, 53, 53, 49, 51, 51, 51, 48, 56, 48, 52, 101, 97, 55, 45, 98, 100, 54, 54, 45, 52, 100, 53, 100, 45, 57, 49, 101, 98, 45, 98, 50, 100, 99, 102, 101, 50, 53, 49, 53, 98, 51, 56, 5, 64, 1]),
  type: "TYPE_CHAT_MESSAGE",
}
{
  clock: 1662469470975n,
  timestamp: 1662469470975n,
  text: "Test",
  chatId: "0x029f196bbfef4fa6a5eb81dd802133a63498325445ca1af1d154b1bb454295513330804ea7-bd66-4d5d-91eb-b2dcfe2515b3",
  messageType: "COMMUNITY_CHAT",
  contentType: "TEXT_PLAIN",
}
		</code>
  </pre>
</details>

### nwaku version/commit hash
- https://github.com/status-im/nwaku/commit/f4e9d395245ac1b83de002372c39b43bd29e80bd
  - https://ci.infra.status.im/job/nim-waku/job/deploy-status-test/19/

### Additional context
- queries were sent from `js-waku@^0.25.0`

**Comment by LNSD** [comment]
What I understand is that querying three different nodes, the number of messages returned is different between them.

I have some questions related to that, @felicio:
- Are these nodes connected to the other two nodes via relay?
- The messages we are trying to retrieve do they have the message timestamp (aka sender timestamp) field set when sent?

**Comment by felicio** [comment]
@LNSD 

> Are these nodes connected to the other two nodes via relay?

I'd say yes, based on https://github.com/status-im/infra-status/blob/master/ansible/group_vars/status.yml#L45. @jakubgs could you please confirm?

I haven't learned how to get this info from the nodes yet 😅. Maybe via a RPC method?

> The messages we are trying to retrieve do they have the message timestamp (aka sender timestamp) field set when sent?

The one with `timestamp: 1662976850017999872n` yes, as it was sent via `status-js` > `js-waku`.

The other ones were sent from `status-go`, and based on https://github.com/status-im/status-go/blob/846029692c8a2ec5f9adb1b6781498f265c44b75/eth-node/types/rpc.go I would say no. Moreover, I think they must have been sent as Waku v1 messages. @cammellos or @iurimatias could you please confirm?

**Comment by LNSD** [comment]
New metrics were added to the waku store in a recently merged PR #1148:

* Restored "messages count" metric
* Added "store insertion time" and "store query time" metrics (both in milliseconds).

With this, we hope to improve the observability of the waku store protocol.

**Comment by jakubgs** [comment]
@felicio :
```
admin@node-01.do-ams3.status.test:~ % /docker/nim-waku/rpc.sh get_waku_v2_admin_v1_peers | jq '.result[].multiaddr'
"/dns4/node-01.gc-us-central1-a.status.test.statusim.net/tcp/30303/p2p/16Uiu2HAmGDX3iAFox93PupVYaHa88kULGqMpJ7AEHGwj3jbMtt76"
"/ip4/134.209.133.76/tcp/9000/p2p/16Uiu2HAmLwrpAgicPqsNtGprzGVudfFAPFT9iQ972MtVDcpn4Ucx"
"/dns4/node-01.ac-cn-hongkong-c.status.test.statusim.net/tcp/30303/p2p/16Uiu2HAm2BjXxCp1sYFJQKpLLbPbwd5juxbsYofu3TsS3auvT9Yi"
```

**Comment by felicio** [comment]
@LNSD 

> The other ones were sent from status-go, and based on https://github.com/status-im/status-go/blob/846029692c8a2ec5f9adb1b6781498f265c44b75/eth-node/types/rpc.go#L7-L19 I would say no.

@cammellos informed me that Waku messages would have timestamp set before sending and confirmed that they would have been bridged.

And I believe, then translated v2 messages would have `timestamp` set at https://github.com/status-im/nwaku/blob/a4860d92a0906e51eb941f84ce840ea03a9feaf5/waku/common/wakubridge.nim#L117.

**Comment by fryorcraken** [comment]
Feedback during Waku e2e meeting is that no missing messages so far since latest improvements.

Please re-open or open new issue if new missing messages are spotted.
