### ISSUE TITLE
chore(rln-relay): metrics collection

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#1182]
### Problem
This issue is to collect performance metrics of the waku-rln-relay protocol. 
This would give us more insights into the network status and the protocol performance in general.

### Acceptance criteria
The following metrics are collected and logged periodically e.g., every minute.

- [x] Number of messages published on the content topic of `/toy-chat/2/luzhou/proto` 
- [x] Number of non-spam messages published on the same content topic
- [x] Number of messages detected as spam within the same content topic
- [x] Number of incoming  messages with invalid proof field
- [x] Number of incoming messages with invalid Epoch
- [x] Number of incoming messages with stale tree root
- [x] Time required for mounting waku-rln-relay
- [x] Proof verification time (and average)
- [x] Proof generation time (and  average)
- [x] The number of times the proof verification is checked

### Possible Solutions
Can use nim-metrics  https://github.com/status-im/nim-metrics

### Research track
Rln-Track

#### Next
Visualizing the metrics collected on the waku test fleets on the waku dashboard.

**Comment by staheri14** [comment]
@rymnc feel free to put yourself as the assignee of this issue.

**Comment by rymnc** [comment]
@staheri14 should we log these metrics to stdout as well?

**Comment by staheri14** [comment]
No need for stdout, I guess when you add periodic logging, they will be part of the logs, and that is fine.
