### ISSUE TITLE
chore: semantic versioning for releases

### ISSUE THREAD

**Issue by mfw78** [status-im/nwaku#1194]
### Background
Many packaging systems (`npm`, `crate`, `go`, etc) use *Semantic Versioning* to ease dependency lookups and facilitate automation between components in complex systems. With release tagging such as `v0.11`, this does not comply with semantic versioning, and may result in breakages in automated packaging systems.

### Details
It is the desire of this issue that the releases and tagging implement [semantic versioning](https://semver.org/).

### Acceptance criteria
Versions adheres to semver, such that:

- [ ] `vx.y.z` for tagged commits.
- [ ] `vx.y.z` for github 'releases'.

**Comment by jm-clius** [comment]
Thanks for this, @mfw78. We are already planning to switch to proper `semver` for the next release: https://github.com/status-im/nwaku/milestone/4.

**Comment by jm-clius** [comment]
Closing, as this forms part of a release that follows semantic versioning.
