### ISSUE TITLE
feat: configuration via environment variables

### ISSUE THREAD

**Issue by mfw78** [status-im/nwaku#1198]
### Problem
I'm always frustrated by the need to use command line arguments in order to configure `nwaku`. Different configuration management / orchestration mechanisms have a multitude of special character considerations, limitations etc, that leads to vendor specific restrictions with respect to command line arguments.

### Suggested solution
Implement a concise configuration engine, including:

- [ ] Sane defaults - no configuration for the base-line is better than having to specify anything.
- [ ] Command line arguments
- [ ] Environment variables
- [ ] Configuration file (TOML, ini, YAML etc).

The method of configuration should take into account the above order of priority to allow for overwriting configuration options when deemed necessary by the system administrator / packager.

### Additional context
This issue has arisen when implementing `dappnode` packaging for `nwaku`. As `dappnode` uses `docker`, it's heavily biased towards environment variable configuration (with command argument configuration being more fragile).

### Acceptance criteria

- [ ] Configuration order of priority (config file < env var < command line argument)
- [ ] Environment variable configuration

**Comment by jm-clius** [comment]
Thanks for this issue, @mfw78. It serves as a very sane blueprint for how to make configuration easier in general (we also need config file examples/demo instructions) and can certainly rethink what "sensible defaults" would entail.

Configuration simplification seems to me to be one of the "most voted" features during the operator trial so far and this issue captures it well. I've included it in the overall tracking item for actions arising from the operator trial: https://github.com/status-im/nwaku/issues/1208

**Comment by LNSD** [comment]
I have created the following issue to track the waku store-related configuration options piece of work: 

* https://github.com/status-im/nwaku/issues/1217

My initial plan is to release it as part of the `v0.13` release.

**Comment by alrevuelta** [comment]
I totally acknowledge the pain in "special character considerations, limitations etc" using CLI flags in different environments. Does having configuration via files (i.e. YAML) solve the problem?

Just trying to understand the need here of having all three i)cli, ii) files and iii) env variables. Perhaps having i) cli and ii) files is enough? Have bad experiences with env variables and adds an extra dimension of complexity + order of priority. So imho adding it has to be properly justified.

wdyt?

**Comment by mfw78** [comment]
Primarily when running in `docker` / kubernetes, environment variables for configuration make things order of magnitudes easier. Otherwise when running simulations with different configurations, there would either have to be a `bash` script to mangle the `cli` parameters, or a script to dynamically generate the configuration.

**Comment by alrevuelta** [comment]
@mfw78 Mind elaborating on the differences between env variables and config file in docker/k8s? imho I actually would prefer a configuration file and if that solves the issue stated in your `Problem` then why add env variables?

**Comment by mfw78** [comment]
@alrevuelta As the initial issue states, I'm approaching this from a dappnode specific perspective. Configuration wizards in dappnode set environment variables only. Otherwise when deploying, a user would have to go in and upload to the container a specific configuration file, which is detrimental to the user experience (or save that a new docker image would have to be created in which a bash script is used to wrangle the environment variables and then pass these as CLI parameters and/or generate an ephemeral configuration file).

As docker images are published for `nwaku`, there should be as few assumptions as possible made about the target environment that these images are going to run in. For some, it may perfectly suit them to start a docker image from the command line, and using CLI parameters or configuration files for such are perfectly fine. There are environments though where those methods of configuration are brittle.

**Comment by LNSD** [comment]
I am taking over this issue 😁

> As docker images are published for nwaku, there should be as few assumptions as possible made about the target environment that these images are going to run in.

Absolutely! I try to conform `nwaku` to the [twelve-factor app](https://12factor.net/) principles. And regarding the configuration, [the III principle](https://12factor.net/config), this is what it says:

> Store config in the environment

I am investigating how to add support for configuring nwaku using env variables. This very likely will be part of the `v0.13.0` release.

**Comment by alrevuelta** [comment]
@mfw78 I see. I actually thought that dappnode could be easily integrated with config files. afaik [prysm](https://github.com/prysmaticlabs/prysm/) doesn't have env variables config and its integrated with dappnode without the user having to manually update the file. correct me if im wrong though.

**Comment by mfw78** [comment]
> Edit: [ref to dappnode prysm package](https://github.com/dappnode/DAppNodePackage-prysm)

You're spot on with the dappnode prysm package, but the way the achieve this is using custom built docker images that effectively just wrap upstream and implement an `entrypoint.sh` bash script that takes the environment it's being passed from dappnode and translates it to CLI parameters.

**Comment by alrevuelta** [comment]
@mfw78 I see. "custom built docker images" is not nice, since the software can be changed and it's not the original image. I wonder if dappnode could have a better integration with config files. But beyond the scope of this issue.

Thanks for the great input!

**Comment by LNSD** [comment]
@mfw78 The functionality has been merged, and it will be available as part of the next released, as promised 😁 


> Environment variables should be prefixed by the app's name. For example, to set the `--tcp-port` configuration we should call `wakunode2` binary as follows:
> 
> ```bash
> WAKUNODE2_TCP_PORT=65000 ./build/wakunode2
> ```
> 
> And this is the configuration precedence order (each item takes precedence over the item below it):
> 
> 1. Commandline options/flags
> 2. Environment variables
> 3. Configuration file (currently, only TOML is supported)
> 4. Default value
> 
> This precedence order also aligns with other languages' de facto standards like [Go's Viper](https://github.com/spf13/viper#:~:text=Viper%20uses%20the,default).
> 

Stay tuned, we are working on rounding the corners and polishing the release.
