### ISSUE TITLE
chore(chat2): enable metrics

### ISSUE THREAD

**Issue by rymnc** [status-im/nwaku#1203]
### Background
The metricsServer and metricsLogging flags are available as configuration parameters but are not setup in the chat2 initialization procedure. Metrics would be useful for those running chat2.

### Details
Enable metricsLogging, similar to -
https://github.com/status-im/nwaku/blob/master/waku/v2/node/wakunode2.nim#L1160-L1161

### Acceptance criteria
- [x] Create a procedure that both wakunode2 and chat2 can use to periodically log rln metrics. 
  - https://github.com/status-im/nwaku/pull/1262
- [ ] Enable the metrics server for chat2
  - https://github.com/status-im/nwaku/pull/1279

**Comment by staheri14** [comment]
Is this issue in progrees? if yes, then please move it to the `in progress` column.

**Comment by rymnc** [comment]
Yes, this issue is in progress. The second step is a *little* more involved, and should be resolved soon
