### ISSUE TITLE
chore: make uniform the store protocol configuration options for nwaku

### ISSUE THREAD

**Issue by LNSD** [status-im/nwaku#1217]
### Background
TBD

### Details
TBD

### Acceptance criteria
TBD

**Comment by jm-clius** [comment]
Great, thanks! One store config-related bug that we'll have to address for `Release v0.12.0` already, is this one: https://github.com/status-im/nwaku/issues/1188 (I'm on it - should be a simple fix).

**Comment by LNSD** [comment]
This issue seems to duplicate https://github.com/status-im/nwaku/issues/1103. Closing this issue in favor of #1103
