### ISSUE TITLE
feat: Use zerokit by default/deploy on test fleet

### ISSUE THREAD

**Issue by fryorcraken** [status-im/nwaku#1227]
### Problem

The Kilic and zerokit RLN implementations are not compatible.

In go-waku, we know use zerokit by default
In the browser (js-waku+js-rln) we can only use zerokit

Which means that browser example such as https://examples.waku.org/rln-js do not work when connecting to the Waku v2 test fleet as kilic is deployed

### Suggested solution

1. Deploy nwaku with zerokit on waku v2 test (and prod for next release)
2. make `RLN=true` compile with zerokit by default

**Comment by rymnc** [comment]
2. has been resolved by https://github.com/status-im/nwaku/pull/1190

We can deploy the changes to the test fleet, after the contracts have been redeployed, right?
cc: @s1fr0 @staheri14

**Comment by rymnc** [comment]
Zerokit has been added to the test fleet and deployed to `wakuv2.test` at the moment. It will be deployed to `wakuv2.prod` with the next release.
