### ISSUE TITLE
feat(rln-relay): Detect disconnection to the Ethereum client and resume updating group state

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#1247]
### Problem

This problem was discovered during testnet2 and it is as follows.
The test fleets fetch all the historical events at the startup, but they fail to fetch any events afterward. 
This causes inconsistency between their group states and other peers.
 
### Suggested solution
It is probably due to some intermittent connections to the Ethereum client. Should investigate more.

### Acceptance criteria
Make sure that a waku node can 1) detect disconnection from the Ethereum client and 2)resume updating the group state after disconnect

**Comment by jakubgs** [comment]
Switched `wakuv2.test` to Infura __temporarily__ for debugging as requested by @rymnc: https://github.com/status-im/infra-nim-waku/commit/9c644e76

**Comment by jakubgs** [comment]
I've reverted to using our own Goerli Geth node: https://github.com/status-im/infra-nim-waku/commit/a0689736

**Comment by jakubgs** [comment]
I have switched the `wakuv2.test` hosts to using the Geth node again: https://github.com/status-im/infra-nim-waku/commit/e4256913
