### ISSUE TITLE
feat(rln-relay): Keep track of the last processed event for membership changes 

### ISSUE THREAD

**Issue by rymnc** [status-im/nwaku#1265]
### Problem
To allow reconnections to the Ethereum node, we need to keep a track of the last event that was processed re: Membership changes. This allows the node to reconnect, and resume the tree sync from the last processed event to avoid inconsistencies in the tree root.

### Suggested solution
The suggested solution would involve a cursor which is set back to 0 after each block is processed by the node. We already keep a track of the last block processed, which can then be used to resubscribe to the events starting from that block.

### Alternatives considered
We could process blocks atomically.

### Additional context
None

### Acceptance criteria
- [x] Maintain an event index cursor for each tree update

**Comment by staheri14** [comment]
Changed the state of this issue assuming it is in progress. If not, please move it back to the Backlog.

**Comment by staheri14** [comment]
> The suggested solution would involve a cursor which is set back to 0 after each block is processed by the node.

I remember we agreed that cursor to be an always increasing value that keeps track of the index of the last inserted pk. 
Why do we need to reset it back to 0 after processing each block?

**Comment by rymnc** [comment]
> I remember we agreed that cursor to be an always increasing value that keeps track of the index of the last inserted pk. Why do we need to reset it back to 0 after processing each block?

That works too. It would not make a difference between the too. If you prefer it, I can use the index of the last inserted pk

**Comment by staheri14** [comment]
If there is no specific benefit regarding the per-block cursor,  then a global cursor for the index of the last inserted pk is a more flexible solution (e.g., it is agnostic to how group synchronization works, and it would be also easily adaptable to any alternative solutions we want to use for the calculation of  window of acceptable roots)

**Comment by rymnc** [comment]
@s1fr0, with #1266, the roots will change on a per block basis. Although, I do understand your point for membership deletions. The event emitted on membership deletions looks to have the same structure as registrations - Maybe we could track registrations and deletions separately. 
This logic comes handy in `Step 2` of your solution, where the tree is cloned, and we lose connection to the ethereum node. The index allows us to resume tree changes to the cloned tree, instead of playing back the whole block. Although, playing back the whole block would have a minimal overhead, and would be the more correct way to have a consistent tree. wdyt @staheri14 @s1fr0 ?

**Comment by rymnc** [comment]
Agreed. Can we then deprecate this feature in favor of #1266 and process blocks atomically?

**Comment by staheri14** [comment]
@s1fr0 @rymnc 
Both solutions are correct and they are not in conflict at all.
- Atomic processing of blocks (which is mentioned by @s1fr0 ) has already been planned out in these issues https://github.com/status-im/nwaku/issues/1306 and https://github.com/status-im/nwaku/issues/1266 and are going to be implemented after this PR.
- Keeping track of the index of the last seen registered membership commitment is somewhat orthogonal to the atomic processing of blocks. It is more about state keeping for the waku rln relay node e.g., to check whether registration events arrive out of order or not (with a high probability they will be in order, but that is just a sanity check from our side). There are other future usecase to it, for instance, to implement a req/response protocol where waku nodes can query a portion of the tree from each other without actually having connections to any Eth client. 

Does that address everyone's concerns?
