### ISSUE TITLE
Rln-Relay features/refactoring targeted for release 0.13.0 

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#1268]
### Problem
This is to keep track of the rln-relay features to be ready for integration in the next nwaku release  0.13.0.

Below is a non-exclusive list of features and refactoring tasks that would be good to be tackled for the next release. 
The task assignments are tentative.
- [x] Move from Infura to our in-house Goerli Ethereum node https://github.com/status-im/nwaku/issues/1269 (@rymnc)
- [x] Tree root validation + keeping track of the state of the tree 
  - [x]  https://github.com/status-im/nwaku/issues/1265 (@rymnc)
      - [x] https://github.com/status-im/nwaku/pull/1296 (@rymnc)
  - [x] https://github.com/status-im/nwaku/issues/1266
    - [x] https://github.com/vacp2p/zerokit/pull/63 (@rymnc)
    - [x] https://github.com/status-im/nwaku/pull/1349 (@rymnc)
- [x] RLN relay metric collection and visualization on the dashboard
  - [x] https://github.com/status-im/nwaku/pull/1275 (@rymnc)
- [x] Metrics on chat2
  - [x] https://github.com/status-im/nwaku/issues/1203 (@rymnc)
- [x] Key store for rln credential management. 
If we could integrate keystore, then the following issues will be addressed as well:
  - [x] https://github.com/status-im/nwaku/issues/1113 (@s1fr0)
  - [x] https://github.com/status-im/nwaku/issues/1021 (@s1fr0)
  - [x] https://github.com/status-im/nwaku/pull/1285 (@s1fr0)
- [x] Enabling zerokit by default 
  - [x] https://github.com/status-im/nwaku/issues/1061 (@s1fr0)
  - [x] https://github.com/status-im/nwaku/issues/1227 (@s1fr0)
  - [x] addressing 1061 would naturally resolve https://github.com/status-im/nwaku/issues/1213 (@s1fr0)
- [x] Better error handling by rln-relay modules
  - [x] https://github.com/status-im/nwaku/issues/1053 (@rymnc)
  - [x] https://github.com/status-im/nwaku/issues/1189 (@rymnc)
    - [x] https://github.com/status-im/nwaku/pull/1321 (@rymnc)

- [x] https://github.com/status-im/nwaku/issues/1222 (@LNSD)
- [x] removing killic lib
  - [x] https://github.com/status-im/nwaku/issues/1314 (@s1fr0)
  - [x] https://github.com/status-im/nwaku/pull/1365 (@s1fr0)
- [x] Removing ganache from makefile, and moving it to the test suites
  - [x] #1347 (@s1fr0)

There are a couple of other low-hanging fruits which we can attempt in case the above list is completed earlier than the deadline.
### Acceptance criteria
Getting the listed features ready and tested by the indicated deadline below. 
Making sure there is no regression regarding the added features on the waku v2 fleets.

### Deadline
November 8th (one week prior to the next release date).
cc: @jm-clius, @oskarth

**Comment by staheri14** [comment]
The task assignment above is tentative.

**Comment by staheri14** [comment]
Please add your suggested tasks as a comment to this issue. Once prioritized, then we can update the issue description.

**Comment by staheri14** [comment]
@rymnc Any comments on this?

**Comment by staheri14** [comment]
> The issue to be investigated that we discussed internally: #1270

Added to the issue.

**Comment by LNSD** [comment]
The following issue covers the credentials store implementation; in it, you can find my comment based on the work assessment I did: #1021

**Comment by rymnc** [comment]
> @rymnc Any comments on this?

Looks like a great roadmap!

**Comment by jm-clius** [comment]
Thanks for great progress team! As far as I know this has been reviewed and everything we want to include in the revised list for `0.13.0` has been merged? Could we get this issue in a state where we can close it by release time (EOB Monday 14 Nov)? In other words, any open listed issues/tasks should move to a new tracking issue (if applicable). Closing this issue is necessary to close the release milestone.

**Comment by rymnc** [comment]
> Thanks for great progress team! As far as I know this has been reviewed and everything we want to include in the revised list for `0.13.0` has been merged? Could we get this issue in a state where we can close it by release time (EOB Monday 14 Nov)? In other words, any open listed issues/tasks should move to a new tracking issue (if applicable). Closing this issue is necessary to close the release milestone.

https://github.com/status-im/nwaku/issues/1376 tracking here now

**Comment by staheri14** [comment]
Thanks @rymnc, for opening the tracking issue; the current one can be closed.

**Comment by staheri14** [comment]
> No change in #1367 was merged to master (closed draft PR) and hence it is not relevant for release v0.13.0.
> 
> IMO it should not be part of this issue and should be moved instead to #1376

@s1fr0 I think it is not gonna show up as part of the release as it is not merged. What is in this issue is just the description of the efforts that were made.  WDYT?

**Comment by staheri14** [comment]
I see that @rymnc has moved the refactoring part to the new issue, so I just closed this one.
