### ISSUE TITLE
infra(rln): unstable Goerli Ethereum Client

### ISSUE THREAD

**Issue by s1fr0** [status-im/nwaku#1269]
### Problem
Our Goerli Ethereum client listening on `ws://linux-01.he-eu-hel1.nimbus.prater.statusim.net:9547` is often unresponsive and connection might time-out.

### Impact
Impossibility to retrieve the latest state of RLN membership contract e.g., old and new registrations in order to keep updated the local RLN Merkle tree required to produce valid RLN proofs.

### To reproduce
```
mkdir -p /tmp/goerli-test && cd /tmp/goerli-test
yarn add ethers
node
const ethers = require('ethers')
const p = new ethers.providers.WebSocketProvider('ws://linux-01.he-eu-hel1.nimbus.prater.statusim.net:9547')
await p.getBlockNumber()
```

### Expected behavior
Connection is stable and responsive as new events appear on the blockchain.

### nwaku version/commit hash
nwaku [44e49a0](https://github.com/status-im/nwaku/tree/44e49a023587257a9d275dc653689f825d05bbf6)

**Comment by staheri14** [comment]
This issue should be mostly be addressed after the integration of https://github.com/status-im/nwaku/issues/1265

**Comment by staheri14** [comment]
Do we really have access to those Ethreum clients? I was under the impression that the waku v2 test fleets have exclusive access @jakubgs

**Comment by staheri14** [comment]
I see, no need to revoke your access. Just wanted to make sure the issue is not due to inaccessibility.

**Comment by staheri14** [comment]
While @rymnc is looking into https://github.com/status-im/nwaku/issues/1265, it would be good to have @jakubgs insights as to what causes such connectivity issues on the Ethereum clients.

**Comment by jakubgs** [comment]
I have extended the values for the `--ws.origins` flag for Geth nodes to include VPN IP and hostnames:

- https://github.com/status-im/infra-role-geth/commit/45838211 - extend --ws.origins value to be same as rpc
- https://github.com/status-im/infra-nimbus/commit/c6106925 - set explicit but wider values for websocket origins

Maybe that was the issue, not sure yet.

**Comment by rymnc** [comment]
Updating the ws.origins flag to include origins other than localhost has fixed the issue.

**Comment by jakubgs** [comment]
Shouldn't we open an issue with `go-ethereum` about it not retuning an error like RPC or AuthRPC would?

**Comment by jakubgs** [comment]
I have switched the `wakuv2.test` hosts to using the Geth node again: https://github.com/status-im/infra-nim-waku/commit/e4256913
