### ISSUE TITLE
bug: vendor/zerokit/target/release/librln.so

### ISSUE THREAD

**Issue by fryorcraken** [status-im/nwaku#1372]
### Problem

When building nwaku master HEAD in GitHub action CI to spot any incoming incompatibility:

```
PROC=$(nproc --all 2>/dev/null || echo 2)
make -j$PROC update
NIMFLAGS="-d:chronicles_colors=off -d:chronicles_sinks=textlines -d:chronicles_log_level=TRACE" make -j$PROC wakunode2
```

Once compiled, getting following error:

```
could not load: vendor/zerokit/target/release/librln.so
```

See CI action: https://github.com/waku-org/js-waku/actions/runs/3442478506/jobs/5743098617

### Impact

Not great :)

### Reproduce

See https://github.com/waku-org/js-waku/pull/1017

### Screenshots/logs

See CI action: https://github.com/waku-org/js-waku/actions/runs/3442478506/jobs/5743098617

### nwaku version/commit hash

master HEAD

**Comment by fryorcraken** [comment]
Also, do I still need to set the NIMFLAGS to get trace logs or is that deprecated?

**Comment by jm-clius** [comment]
cc @s1fr0 @rymnc (haven't reproduced myself, but please take a look).

**Comment by jm-clius** [comment]
> Also, do I still need to set the NIMFLAGS to get trace logs or is that deprecated?

Deprecated. You can now use `--log-level` runtime to choose your desired log level.

**Comment by rymnc** [comment]
Will try to reproduce today.

**Comment by jm-clius** [comment]
>  another quite reasonable explanation is that we removed a necessary when defined(rln) flag in the kilic lib removal.

Most likely explanation IMO. The path shouldn't matter if RLN is not defined.

**Comment by rymnc** [comment]
@fryorcraken, can you update your PR (https://github.com/waku-org/js-waku/pull/1017) to use https://github.com/status-im/nwaku/pull/1373 as the origin?

**Comment by fryorcraken** [comment]
> @fryorcraken, can you update your PR ([waku-org/js-waku#1017](https://github.com/waku-org/js-waku/pull/1017)) to use #1373 as the origin?

Finally got it to happen:

```
Run uname -a
  uname -a
  cd nwaku/buildabove
  ./wakunode2 --help
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    NWAKU_VERSION: v0.11
    NODE_JS: 16
    DEBUG: waku*
    npm_config_cache: /home/runner/.npm
Linux fv-az224-67 5.15.0-1022-azure #27~20.04.1-Ubuntu SMP Mon Oct 17 02:03:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
/home/runner/work/_temp/13525db4-816b-4f32-9b6c-139625b243db.sh: line 2: cd: nwaku/buildabove: No such file or directory
Error: Process completed with exit code 1.
```

https://github.com/waku-org/js-waku/actions/runs/3457913371/jobs/5771813882

Not sure if nwaku bug or issue with the checkout. let me know.

**Comment by rymnc** [comment]
Path should be `nwaku/build` not `nwaku/buildabove` 🤔

**Comment by fryorcraken** [comment]
> Path should be `nwaku/build` not `nwaku/buildabove` thinking

My brain did not even register. That's what happened when you multitask.. ok I pushed again. :crossed_fingers:

**Comment by rymnc** [comment]
Addressed in #1373, @fryorcraken please close this if you agree

**Comment by rymnc** [comment]
Yes, and we have 2 options to solve the path issue -
- As you and @LNSD have mentioned, use rln as a static lib
- Use an env var to indicate the absolute path of librln

**Comment by LNSD** [comment]
> As you and @LNSD have mentioned, use rln as a static lib

This is a requirement from product for RLN productionalization

**Comment by fryorcraken** [comment]
Happy if this closed against an issue support of rln as static lib. Otherwise IMO it should remain open.

**Comment by jm-clius** [comment]
Closing, as #1380 has been opened
