### ISSUE TITLE
Implement proper connection management

### ISSUE THREAD

**Issue by kdeme** [status-im/nwaku#18]
Currently, we just directly connect to the fleet once.
This means, that if no discovery is used (and it general isn't as it differs from the discovery in status-go), that we won't reconnect on dropped connections.

**Comment by kdeme** [comment]
I don't think anything was done here.

**Comment by oskarth** [comment]
We did a clean up of old issues hence closing. This is for Waku v1 right? There is some peer management @jm-clius has done for v2. v1 isn't really a priority, unless it is a need for the bridge. Do you disagree?

**Comment by kdeme** [comment]
Yes, for Waku v1. I don't really care how we deal with unsolved tickets, that is icebox and leave open, or just close.

But if we close it, then we should add some tag `not-fixed` or so, to make that clear.

**Comment by oskarth** [comment]
@jm-clius can we close this issue and remove the `waku-1` tag?

**Comment by jm-clius** [comment]
Agree. Closing.
