### ISSUE TITLE
Improve Cheque Functionality in SWAP Protocol

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nwaku#620]
As a follow up to #398 

**Problem**
Currently, the cheques being sent by the issuing peer are not being acknowledged by the recipients. So there is no way to disconnect the peer If payment was not made or verify receipt if a payment was actually made. 

**Suggestion**
- Acknowledge receipt of the cheque and log the id of the issuer.
- Include the public key of the issuer as a property in the cheque Object. 
- Verify the abi signature in the cheque object using the issuer's public key.
- Disconnect Peer if signature verification fails, or no cheque was received.

**Comment by jm-clius** [comment]
Closing, as no one is looking at this.
