### ISSUE TITLE
Fetch Swap Address from Swap Contracts Module

### ISSUE THREAD

**Issue by EbubeUd** [status-im/nwaku#649]
**Problem**
Currently, while making payment, the swap address is being hard coded within the SWAP protocol. In a bid to better structure the Send Cheque function, We want to get rid of the Hard coded addresses within the SWAP protocol and replace them with references to the actual value using the Swap Contracts Module / nim-web3. 

**Solutions**
A solution to this is to create a function in the swap contracts module, responsible for returning the swap address of a user. 
For now, the swap address can be hardcoded in the swap contracts module  till an in depth improvement is done on the smart contracts and scripts for interaction. But this is a step forward in achieving the ultimate goal for sending / receiving cheques.

**Comment by jm-clius** [comment]
Closing, as no-one is working on this.
