### ISSUE TITLE
JSON RPC calls fails when timestamp is an integer

### ISSUE THREAD

**Issue by D4nte** [status-im/nwaku#691]
# Problem

When using `post_waku_v2_relay_v1_message` and passing a timestamp, the call can fail if the passed number is an integer:

```
DBG 2021-08-05 01:23:45.001+00:00 Error occurred within RPC                  tid=4795 file=router.nim:85 methodName=post_waku_v2_relay_v1_message err="Parameter [timestamp] expected JFloat but got JInt"
```

Note that there is no difference between integers and floats in the [JSON Datatype definition](https://www.w3schools.com/js/js_json_datatypes.asp).

From a client implementation point of view, it does not seem possible to alter the JSON value of a JavaScript number when it is an integer (.e.g adding `.0` to it).

# Solution

Accept JSON numbers, both floats and integers.

**Comment by oskarth** [comment]
@jm-clius thoughts on this one?

**Comment by oskarth** [comment]
https://github.com/vacp2p/rfc/issues/448

**Comment by jm-clius** [comment]
As Oskar mentioned above, data type for timestamp is still under discussion in https://github.com/vacp2p/rfc/issues/448. Other use-cases:
1. Users of API should be able to choose not to have the sender timestamp set.
2. Users of API should be able to set the timestamp themselves.
3. Users of API should be able to have the client set the timestamp.

(1) and (2) can be addressed by making the timestamp field optional. (3) requires a bit more thinking for a clean design.

**Comment by oskarth** [comment]
For 3 I think this probably needs to be a boolean flag, i.e. `useNodeTimestamp`.

**Comment by jm-clius** [comment]
Timestamp format has been changed to int64. Closing.
