### ISSUE TITLE
Investigate fleet log anomalies

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#703]
Relates to #695

### Problem

The following log anomalies are seen on fleet nodes:
1. Whenever a remote peer dials a fleet peer:
```
failed to store peers topics="wakupeers" tid=1 file=peer_manager.nim:44 err="failed to encode: Failed to encode public key"
```
Fleet peers should not attempt to store/manage remote peers that dial them (peer storage is only for configured/discovered peers)

2. Scattered throughout the logs, but especially at periods with high message rates (see #702):
```
failed to store messages topics="wakustore" tid=1 file=waku_store.nim:456 err="failed to prepare"
```

3. When querying history via RPC:
```
DBG Using SWAPAccounting query topics="wakunode" tid=3852 file=wakunode2.nim:334
ERR no suitable remote peers topics="wakustore" tid=3852 file=waku_store.nim:713
```
There should be no attempt to perform accounting when querying locally via RPC.

**Comment by oskarth** [comment]
Revisit log hygiene, don't do more than TRC for a given message (e.g.)

**Comment by jm-clius** [comment]
Closing, as remaining work captured in https://github.com/status-im/nwaku/issues/983
