### ISSUE TITLE
High latency (minutes) on Waku Relay (prod fleet)

### ISSUE THREAD

**Issue by D4nte** [status-im/nwaku#736]
I had reports of latency being in the orders of minutes when using the prod fleet.

I can confirm that when running two instances of js-waku each connected to the following prod fleet nodes:
- `/dns4/node-01.gc-us-central1-a.wakuv2.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAmVkKntsECaYfefR1V2yCR79CegLATuTPE6B9TxgxBiiiA`
- `/dns4/node-01.do-ams3.wakuv2.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e`

The latency was indeed over 30s and several messages are just dropped.

I also confirmed this happens when using chat2 connected to one node, messages are not received if connected to another node.

No problem when both local nodes are connected to the same prod fleet node.

**Comment by D4nte** [comment]
Issue occurred again now.

Using https://status-im.github.io/js-waku/

Connected to:
- `/dns4/node-01.ac-cn-hongkong-c.wakuv2.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD`
- `/dns4/node-01.do-ams3.wakuv2.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e`

Messages over relay take ~5s to travel

**Comment by jm-clius** [comment]
Closing, as this specific issue was addressed successfully. The current slow fleet incidents are unrelated and tracked elsewhere: https://github.com/status-im/infra-nim-waku/issues/50
