### ISSUE TITLE
Waku v1: Mailservers

### ISSUE THREAD

**Issue by decanus** [status-im/nwaku#75]
# Problem

Currently the waku v1 node does not allow being run as a mailserver.

# Acceptance Criteria

Waku v1 can be run with as a mailserver. This should be up to [spec](https://specs.vac.dev/specs/waku/mailserver.html).

# Notes

Experimental work can be found here: https://github.com/status-im/nim-waku/pull/33, parts of this should be usable for implementing a real mailserver.

**Comment by oskarth** [comment]
cc @iurimatias fyi

**Comment by oskarth** [comment]
Possible duplicate https://github.com/status-im/nim-waku/issues/8

**Comment by oskarth** [comment]
Closing as wontfix, focus is on Waku v2

cc @jm-clius fyi
