### ISSUE TITLE
`nwaku` operator guide

### ISSUE THREAD

**Issue by jm-clius** [status-im/nwaku#869]
One of the main obstacles to `nwaku` being an easy-to-install-use-and-maintain Waku v2 client for operators is lack of clear documentation. Existing documentation, although constantly improving, is often incomplete, unclear or difficult to find. We need a set of documents in a single place that clearly sets out for operators how to set up and dimension their own `nwaku` nodes for different protocols, how to monitor and maintain those nodes, and where to turn for support.

We could (and should) use the [Nimbus book](https://nimbus.guide/) as inspiration here.

Related to https://github.com/status-im/nim-waku/issues/828

**Comment by D4nte** [comment]
As part of this documentation, we should provider documentation on how one setup their own domain name for discovery purposes: Create an ENR for one's node, create an ENR tree using other's ENRs and link to other domains.

**Comment by jm-clius** [comment]
The operator guide has been published. A laundry list of possible improvements/additions being tracked here: https://github.com/status-im/nwaku/issues/1003
