### ISSUE TITLE
Dynamic rln-relay groups with local tx management (no wallet)

### ISSUE THREAD

**Issue by staheri14** [status-im/nwaku#894]
# Problem
This issue details the first step towards adding support for dynamic group management in rln-relay (aligned with https://github.com/status-im/nim-waku/issues/827). 
Everything will be tested against a test Eth network e.g., Ropsten.  Since nodes will transact on a test network where no real ether and fun is involved, we can safely delay the wallet integration in the favor of doing more focused work on contract event listening (a bit of diversion from the initial plan set out in #827). We assume rln-relay nodes will pass their Eth private keys for the Ropsten test network to the wakunode. The nim-waku node handles the registration and deletion transactions. Part of this logic i.e., tx management from a nim-waku node using nim-web3 is already implemented, so this allows us to concentrate on the event listening component.

The goal of this step is 1) to replace the hardcoded membership tree with a membership contract 2) to implement the necessary logic that enables a nim-waku node to listen to the events emitted from a membership contract. 

# Acceptance Criteria
- [x] Nodes running rln-relay are able to fetch the latest state of the contract and construct their tree
- [x] Nodes running rln-relay are able to listen to the contract and dynamically update their membership tree locally

# Next
In the next phase, the wallet integration will be investigated i.e., https://github.com/status-im/nim-waku/issues/819

cc: @oskarth

**Comment by jm-clius** [comment]
@staheri14 seems like all related tasks are done. Can this be closed?

**Comment by staheri14** [comment]
@jm-clius Right, going to close it.
