### ISSUE TITLE
Makefile: `NIM_PARAMS` override

### ISSUE THREAD

**Issue by kaiserd** [status-im/nwaku#925]
This issue aims to solve a generalization of the problem pointed out in #921.

## Motivation

Makefile variables can be [overridden](https://www.gnu.org/software/make/manual/make.html#Overriding) by command line arguments.
[The Dockerfile](https://github.com/status-im/nim-waku/blob/d0cf3ed1f9299618bbab920c66ee06372f24c1fd/Dockerfile#L21), for instance, overrides `NIM_PARAMS`.

However, some of the parameters added to `NIM_PARAMS` should be fixed for `nwaku`.
These are especially parameters like `-d:discv5_protocol_id:d5waku` which set values that are generic in a vendor module (in this case [nim-eth/discv5](https://github.com/status-im/nim-eth/tree/master/eth/p2p/discoveryv5)) but fixed specified by a Waku spec (in this case [33/WAKU2-DISCV5](https://rfc.vac.dev/spec/33/)).

Parameters of this kind have to be manually set by scripts like the Dockerfile.
Overriding `NIM_PARAMS` but not setting important parameters might lead to confusing hard-to-find errors.

## Suggested solution

Add a new variable holding fixed parameters to the Makefile. This variable would be marked with the  [`override` directive](https://www.gnu.org/software/make/manual/make.html#Override-Directive).

The name could be `NIM_PARAMS_CONST`.

### Alternatives

* document the behaviour but don't introduce changes

## Discussion

Wdyt? I would prefer adding the new variable.
I will implement the preferred solution as soon as I get feedback.

cc @staheri14 @jakubgs @richard-ramos @jm-clius

**Comment by jm-clius** [comment]
I think the issue is that we've (incorrectly) used `NIM_PARAMS` outside the Makefile, where we should have used `NIMFLAGS`: https://github.com/status-im/nimbus-build-system#nimflags. Properly differentiating between `NIMFLAGS` (overrideable) and `NIM_PARAMS` (non-overrideable) is more or less your suggested solution.

**Comment by kaiserd** [comment]
@jm-clius Yes :). My preferred solution would be having two separate Variables.

Should we now change the external uses of `NIM_PARAMS` to `NIM_FLAGS`?
I would also suggest adding the `override` directive to `NIM_PARAMS` then.

@jakubgs wdyt?

I could add a PR changing the Dockerfile. We would have to use `NIM_FLAGS` [here](https://ci.status.im/job/nim-waku/job/deploy-v2-test/build?delay=0sec), too.
