### ISSUE TITLE
nwaku crashed with "Illegal storage access"

### ISSUE THREAD

**Issue by dao** [status-im/nwaku#955]
The logs before this message were all normal get/post calls to json-rpc api, then:

`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

![image](https://user-images.githubusercontent.com/45507/167313597-9a9ac156-d360-4778-a748-1b58ff372364.png)

I've only seen it happen once and have no further context to provide beyond nwaku v0.9

Tagging @Menduist per request

**Comment by LNSD** [comment]
@dao Have you experienced this issue recently? With _v0.10_ or _v0.11_?

**Comment by fryorcraken** [comment]
More recent occurrence reported in https://github.com/status-im/nwaku/issues/1188

Tracking in issue above.
