### ISSUE TITLE
Add --version flag

### ISSUE THREAD

**Issue by dao** [status-im/nwaku#969]
It can be difficult to recall which version of nwaku you're running where. A `--version` flag would make it easy to check.

**Comment by jm-clius** [comment]
@kaiserd would the `get_waku_v2_debug_v1_version()` RPC call be useful here? It seems as if it's not added to RFC16 yet?

**Comment by kaiserd** [comment]
@jm-clius yes. I could add a `--version` flag that prints the same info as the RPC call. And yes, RFC16 has not been updated. Can do that, too.

**Comment by dao** [comment]
This RPC does indeed return "v0.9". This, however, is of little help given that all changes since march 31st are still considered v0.9, with no finer grained version numbers in between. This would be ok if you could return the commit hash as well

**Comment by kaiserd** [comment]
But as you requested, having a `--version` flag is nice to have, too :).

**Comment by kaiserd** [comment]
See #970

Example:

```
./build/wakunode2 --version
version / git commit hash: 062668
```

It will print the version, if the current commit is tagged.

**Comment by kaiserd** [comment]
@dao When testing the RPC call, did you compile the current master branch? It should return the commit hash in this case.
Could it be that you actually have version v0.9? It only prints the version, if the current commit hash is tagged with it.

**Comment by dao** [comment]
> @dao When testing the RPC call, did you compile the current master branch? It should return the commit hash in this case. Could it be that you actually have version v0.9? It only prints the version, if the current commit hash is tagged with it.

Ah ok yes, I must have v0.9 release. Thanks!

**Comment by kaiserd** [comment]
Also added the specification for the version call in RFC 16: https://github.com/vacp2p/rfc/pull/505

**Comment by kaiserd** [comment]
Added feature in #970
