### ISSUE TITLE
Memory leak in wakunodev2

### ISSUE THREAD

**Issue by dmh1974** [status-im/nwaku#978]
I did a clone and compile on May 5th... been running ok, but the node eventually gets killed. I noticed since messaging has increased on the testnet the issue has exacerbated... Memory slowly ticks up at about .1% every few minutes. If I increase store-capacity (did some tests at the 1 million mark) the mem issue further exacerbates. 

I am using this current cl 

./build/wakunode2 --websocket-secure-support=true --websocket-secure-key-path="/etc/letsencrypt/live/procloud.net/privkey.pem" --websocket-secure-cert-path="/etc/letsencrypt/live/procloud.net/fullchain.pem" --store=true --persist-messages=true --nodekey="041059f772955684b0db9edb17bd76a0673d32358f8f841c9166502170ba8532ceace09ade97590d7a8663a0bf7cdd0a9292fa8e06561100421f53b296af039a7c" --db-path="./dbs/db1" --discv5-discovery=true --discv5-bootstrap-node="enr:-JK4QAmmBzjI8YAKKT-9pH_-a5y-9lSjNyY8dNd45AW1M6BhbhPtfGDQrLD73ZjgRKqqmRRAvKiUmSA-5hKoZfDhPqwBgmlkgnY0gmlwhGia74CJc2VjcDI1NmsxoQNYImLJllfa9siWWAIjBhyX4y5S3qgLkwKJFBjzf_6ZMYN0Y3CCdl-DdWRwgiMohXdha3UyDw" --persist-peers=true --dns4-domain-name="dev-waku.procloud.net" --nat="extip:192.81.208.68" --dns-discovery:true --dns-discovery-url:enrtree://AOFTICU2XWDULNLZGRMQS4RIZPAZEHYMV4FYHAPW563HNRAOERP7C@test.nodes.vac.dev

**Comment by jakubgs** [comment]
Yep, it does appear so. I saw node be killed by OOM on `node-01.ac-cn-hongkong-c.wakuv2.prod`:
```
[1541129.269509] runc:[2:INIT] invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=0
[1541129.269530]  oom_kill_process.cold+0xb/0x10
[1541129.269623] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[1541129.269633] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=3628e964f52ca7b2161e6e4104952db8c4298df5a798b05a4ec9ac405539a8a6,mems_allowed=0,oom_memcg=/docker/3628e964f52ca7b2161e6e4104952db8c4298df5a798b05a4ec9ac405539a8a6,task_memcg=/docker/3628e964f52ca7b2161e6e4104952db8c4298df5a798b05a4ec9ac405539a8a6,task=wakunode,pid=1370096,uid=100000
[1541129.269646] Memory cgroup out of memory: Killed process 1370096 (wakunode) total-vm:3505844kB, anon-rss:1409504kB, file-rss:0kB, shmem-rss:0kB, UID:100000 pgtables:6892kB oom_score_adj:0
[1541129.480586] oom_reaper: reaped process 1370096 (wakunode), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
And it's running low store capacity limit:
```
admin@node-01.ac-cn-hongkong-c.wakuv2.prod:~ % grep capacity /docker/nim-waku-v2/docker-compose.yml
      --store-capacity=10000

admin@node-01.ac-cn-hongkong-c.wakuv2.prod:~ % d inspect statusteam/nim-waku:deploy-v2-prod | jq '.[].Config.Labels.commit'
"063c91aa"
```
Really clear memory leak:

![image](https://user-images.githubusercontent.com/2212681/170051982-b488a151-0ba2-4b96-ba3f-31b3b8b06f57.png)

**Comment by jm-clius** [comment]
Locally comparing different configurations to pinpoint most likely source of leak:
1. nwaku node with store, discv5 and DB
2. nwaku node with store and DB but no discv5
3. nwaku node without a store (but with discv5)
4. nwaku node with store, discv5 but no DB

Too early to say for sure, but it seems as if the leak occurs only for (1) and (3) - an indication that it's somehow related to the DB functionality.

Worth noting that the DB files themselves do not actually grow beyond their maximum size, as determined by the store capacity.

**Comment by dmh1974** [comment]
fyi, i rf'd and did a fresh clone and compile to check last merge

the issue is still present.

i havent looked, but i reckon incoming messages are being put in array somewhere thats not getting pruned, or some metadata is being left behind.. if you have some debug ability to watch all the declared variables you may be able to track it down pretty quick

**Comment by jm-clius** [comment]
Have started running the node with `heaptracker`. Top memory allocation indeed comes from SQLite:

```
sqlite3MemMalloc
  at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:23771
  in /mnt/c/source/status-im/nim-waku/build/wakunode2
```

which seems to confirm the observation that leak occurs only when DB is enabled.
Continuing with the investigation.

**Comment by jm-clius** [comment]
Partial backtrace:

```
    mallocWithAlarm
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:27653
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    sqlite3Malloc
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:27683
    sqlite3Malloc
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:26039
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    dbMallocRawFinish
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:27951
    sqlite3DbMallocRawNN
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:28033
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    sqlite3DbMallocRawNN
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:27987
    tokenExpr
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:154975
    yy_reduce
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:159061
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    sqlite3Parser
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:159923
    sqlite3RunParser
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:161204
    sqlite3Prepare
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:129503
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    sqlite3LockAndPrepare
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:129582
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    sqlite3_prepare_v2
      at /mnt/c/source/status-im/nim-waku/vendor/nim-sqlite3-abi/sqlite3.c:129667
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    prepareStmt__usCBg6gsICqyhwz6pSm2Sg
      at /mnt/c/source/status-im/nim-waku/waku/v2/node/storage/sqlite.nim:203
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    put__CvLxyRQgY3cdMoDlyMeVxA
      at /mnt/c/source/status-im/nim-waku/waku/v2/node/storage/message/waku_message_store.nim:135
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
    handleMessage__5HU2zQKkk6mkjZiQFIFJ3w
      at /mnt/c/source/status-im/nim-waku/waku/v2/protocol/waku_store/waku_store.nim:417
      in /mnt/c/source/status-im/nim-waku/build/wakunode2
```

**Comment by jakubgs** [comment]
Wow, quite the difference:

![image](https://user-images.githubusercontent.com/2212681/171420646-0ea90e39-eaa3-4a38-9af4-f67c62584452.png)

Although to be fair the traffic is much smaller as well:

![image](https://user-images.githubusercontent.com/2212681/171421071-188a9cb9-b30a-4fcc-b6c8-3ce81ba6082f.png)

I'll run `waku-connect` role to make sure peers are connected.
